/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HubRouteImport } from './routes/hub'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HubIndexRouteImport } from './routes/hub.index'
import { Route as HubPermissoesRouteImport } from './routes/hub.permissoes'
import { Route as HubLocaisRouteImport } from './routes/hub.locais'
import { Route as HubContasRouteImport } from './routes/hub.contas'
import { Route as HubConfiguracoesRouteImport } from './routes/hub.configuracoes'
import { Route as ApiUploadLogoRouteImport } from './routes/api/upload-logo'
import { Route as ApiAppsScriptRouteImport } from './routes/api/apps-script'
import { Route as HubPromocoesNovaRouteImport } from './routes/hub.promocoes.nova'
import { Route as HubPromocoesIdRouteImport } from './routes/hub.promocoes.$id'
import { Route as HubDetalhesIdRouteImport } from './routes/hub.detalhes.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HubRoute,
} as any)
const HubPermissoesRoute = HubPermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => HubRoute,
} as any)
const HubLocaisRoute = HubLocaisRouteImport.update({
  id: '/locais',
  path: '/locais',
  getParentRoute: () => HubRoute,
} as any)
const HubContasRoute = HubContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => HubRoute,
} as any)
const HubConfiguracoesRoute = HubConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => HubRoute,
} as any)
const ApiUploadLogoRoute = ApiUploadLogoRouteImport.update({
  id: '/api/upload-logo',
  path: '/api/upload-logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppsScriptRoute = ApiAppsScriptRouteImport.update({
  id: '/api/apps-script',
  path: '/api/apps-script',
  getParentRoute: () => rootRouteImport,
} as any)
const HubPromocoesNovaRoute = HubPromocoesNovaRouteImport.update({
  id: '/promocoes/nova',
  path: '/promocoes/nova',
  getParentRoute: () => HubRoute,
} as any)
const HubPromocoesIdRoute = HubPromocoesIdRouteImport.update({
  id: '/promocoes/$id',
  path: '/promocoes/$id',
  getParentRoute: () => HubRoute,
} as any)
const HubDetalhesIdRoute = HubDetalhesIdRouteImport.update({
  id: '/detalhes/$id',
  path: '/detalhes/$id',
  getParentRoute: () => HubRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hub': typeof HubRouteWithChildren
  '/login': typeof LoginRoute
  '/api/apps-script': typeof ApiAppsScriptRoute
  '/api/upload-logo': typeof ApiUploadLogoRoute
  '/hub/configuracoes': typeof HubConfiguracoesRoute
  '/hub/contas': typeof HubContasRoute
  '/hub/locais': typeof HubLocaisRoute
  '/hub/permissoes': typeof HubPermissoesRoute
  '/hub/': typeof HubIndexRoute
  '/hub/detalhes/$id': typeof HubDetalhesIdRoute
  '/hub/promocoes/$id': typeof HubPromocoesIdRoute
  '/hub/promocoes/nova': typeof HubPromocoesNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/apps-script': typeof ApiAppsScriptRoute
  '/api/upload-logo': typeof ApiUploadLogoRoute
  '/hub/configuracoes': typeof HubConfiguracoesRoute
  '/hub/contas': typeof HubContasRoute
  '/hub/locais': typeof HubLocaisRoute
  '/hub/permissoes': typeof HubPermissoesRoute
  '/hub': typeof HubIndexRoute
  '/hub/detalhes/$id': typeof HubDetalhesIdRoute
  '/hub/promocoes/$id': typeof HubPromocoesIdRoute
  '/hub/promocoes/nova': typeof HubPromocoesNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hub': typeof HubRouteWithChildren
  '/login': typeof LoginRoute
  '/api/apps-script': typeof ApiAppsScriptRoute
  '/api/upload-logo': typeof ApiUploadLogoRoute
  '/hub/configuracoes': typeof HubConfiguracoesRoute
  '/hub/contas': typeof HubContasRoute
  '/hub/locais': typeof HubLocaisRoute
  '/hub/permissoes': typeof HubPermissoesRoute
  '/hub/': typeof HubIndexRoute
  '/hub/detalhes/$id': typeof HubDetalhesIdRoute
  '/hub/promocoes/$id': typeof HubPromocoesIdRoute
  '/hub/promocoes/nova': typeof HubPromocoesNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hub'
    | '/login'
    | '/api/apps-script'
    | '/api/upload-logo'
    | '/hub/configuracoes'
    | '/hub/contas'
    | '/hub/locais'
    | '/hub/permissoes'
    | '/hub/'
    | '/hub/detalhes/$id'
    | '/hub/promocoes/$id'
    | '/hub/promocoes/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/apps-script'
    | '/api/upload-logo'
    | '/hub/configuracoes'
    | '/hub/contas'
    | '/hub/locais'
    | '/hub/permissoes'
    | '/hub'
    | '/hub/detalhes/$id'
    | '/hub/promocoes/$id'
    | '/hub/promocoes/nova'
  id:
    | '__root__'
    | '/'
    | '/hub'
    | '/login'
    | '/api/apps-script'
    | '/api/upload-logo'
    | '/hub/configuracoes'
    | '/hub/contas'
    | '/hub/locais'
    | '/hub/permissoes'
    | '/hub/'
    | '/hub/detalhes/$id'
    | '/hub/promocoes/$id'
    | '/hub/promocoes/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HubRoute: typeof HubRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAppsScriptRoute: typeof ApiAppsScriptRoute
  ApiUploadLogoRoute: typeof ApiUploadLogoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/': {
      id: '/hub/'
      path: '/'
      fullPath: '/hub/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof HubRoute
    }
    '/hub/permissoes': {
      id: '/hub/permissoes'
      path: '/permissoes'
      fullPath: '/hub/permissoes'
      preLoaderRoute: typeof HubPermissoesRouteImport
      parentRoute: typeof HubRoute
    }
    '/hub/locais': {
      id: '/hub/locais'
      path: '/locais'
      fullPath: '/hub/locais'
      preLoaderRoute: typeof HubLocaisRouteImport
      parentRoute: typeof HubRoute
    }
    '/hub/contas': {
      id: '/hub/contas'
      path: '/contas'
      fullPath: '/hub/contas'
      preLoaderRoute: typeof HubContasRouteImport
      parentRoute: typeof HubRoute
    }
    '/hub/configuracoes': {
      id: '/hub/configuracoes'
      path: '/configuracoes'
      fullPath: '/hub/configuracoes'
      preLoaderRoute: typeof HubConfiguracoesRouteImport
      parentRoute: typeof HubRoute
    }
    '/api/upload-logo': {
      id: '/api/upload-logo'
      path: '/api/upload-logo'
      fullPath: '/api/upload-logo'
      preLoaderRoute: typeof ApiUploadLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apps-script': {
      id: '/api/apps-script'
      path: '/api/apps-script'
      fullPath: '/api/apps-script'
      preLoaderRoute: typeof ApiAppsScriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/promocoes/nova': {
      id: '/hub/promocoes/nova'
      path: '/promocoes/nova'
      fullPath: '/hub/promocoes/nova'
      preLoaderRoute: typeof HubPromocoesNovaRouteImport
      parentRoute: typeof HubRoute
    }
    '/hub/promocoes/$id': {
      id: '/hub/promocoes/$id'
      path: '/promocoes/$id'
      fullPath: '/hub/promocoes/$id'
      preLoaderRoute: typeof HubPromocoesIdRouteImport
      parentRoute: typeof HubRoute
    }
    '/hub/detalhes/$id': {
      id: '/hub/detalhes/$id'
      path: '/detalhes/$id'
      fullPath: '/hub/detalhes/$id'
      preLoaderRoute: typeof HubDetalhesIdRouteImport
      parentRoute: typeof HubRoute
    }
  }
}

interface HubRouteChildren {
  HubConfiguracoesRoute: typeof HubConfiguracoesRoute
  HubContasRoute: typeof HubContasRoute
  HubLocaisRoute: typeof HubLocaisRoute
  HubPermissoesRoute: typeof HubPermissoesRoute
  HubIndexRoute: typeof HubIndexRoute
  HubDetalhesIdRoute: typeof HubDetalhesIdRoute
  HubPromocoesIdRoute: typeof HubPromocoesIdRoute
  HubPromocoesNovaRoute: typeof HubPromocoesNovaRoute
}

const HubRouteChildren: HubRouteChildren = {
  HubConfiguracoesRoute: HubConfiguracoesRoute,
  HubContasRoute: HubContasRoute,
  HubLocaisRoute: HubLocaisRoute,
  HubPermissoesRoute: HubPermissoesRoute,
  HubIndexRoute: HubIndexRoute,
  HubDetalhesIdRoute: HubDetalhesIdRoute,
  HubPromocoesIdRoute: HubPromocoesIdRoute,
  HubPromocoesNovaRoute: HubPromocoesNovaRoute,
}

const HubRouteWithChildren = HubRoute._addFileChildren(HubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HubRoute: HubRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAppsScriptRoute: ApiAppsScriptRoute,
  ApiUploadLogoRoute: ApiUploadLogoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
